### ISSUE TITLE
[Req 25]: Als betrokkene wil ik dat ik bij het bezoek aan het ziekenhuis/de zorgverlener alsnog mijn toestemmingskeuze kan registreren als ik dit thuis nog niet heb gedaan

### ISSUE THREAD

**Issue by MLHoekstra** [minvws/generiekefuncties-toestemming#25]
Casus: Tijdens de behandeling in ziekenhuis

· De zorgverlener moet in de instelling de toestemming kunnen registeren. 

· 18% wordt geregistreerd bij de inschrijfbalie of via inschrijfzuilen.

· Om een EPD order op de werklijst te zetten moet het bekend zijn of er een toestemming is geregistreerd.

# Relaties
Zijn specifieker als uitgewerkt in de volgende requirements en daarmee kan deez dus komen te vervallen.
* #26 
* #47

**Comment by Guidonoord** [comment]
Uitleg past niet bij de requirement. De requirement gaat over dat patient zelf nog toestemming wil kunnen vastleggen (ik stel me voor, ergens inloggen met DigiD etc.). De uitleg stelt dat zorgverlener dit namens client moet kunnen doen. Dat zijn twee heel verschillende zaken. De laatste variant moet niet vanuit de client/patient geformuleerd worden en is m.i. een aparte requirement, vanuit een andere stakeholder geformuleerd.

**Comment by marc-smits** [comment]
Voorstel voor herformulering: "Een zorgmedewerker van een instelling kan de patiënt helpen bij het registreren van een toestemming."
