### ISSUE TITLE
[Req 30]: Als zorgverlener heb ik behoefte aan het behoud van een goede vertrouwensrelatie met patiënt/cliënt, door en zorgvuldige omgang met gevoelige patiëntgegevens

### ISSUE THREAD

**Issue by MLHoekstra** [minvws/generiekefuncties-toestemming#30]

**Comment by stevenvegt** [comment]
Zoals behandeld tijdens de werkgroep van 29 maart. Heeft in deze formulering niet voldoende relatie met de OTV.
Mogelijke alternatieve formulering:

> Een OTV mag geen negatieve invloed hebben op de vertrouwensrelatie tussen behandelaar en patient.

@MLHoekstra kun jij dit bekijken?
