### ISSUE TITLE
[Req 31]: Als verantwoordelijke voor de toestemmingenregistratie wil ik op eIDAS hoog niveau kunnen verifiëren of de persoon die online inlogt om toestemming te registreren daartoe geautoriseerd is.

### ISSUE THREAD

**Issue by MLHoekstra** [minvws/generiekefuncties-toestemming#31]
# Volledige omschrijving
Als verantwoordelijke voor de toestemmingenregistratie wil ik op eIDAS hoog niveau kunnen verifiëren of de persoon die online inlogt om toestemming te registreren daartoe geautoriseerd is.

# Overwegingen
* DIGID Substantieel.
* Indirect vertrouwen via Mitz, hoe mee om te gaan?

**Comment by VincentvandenBerg** [comment]
Eis is niet realistisch gezien de huidige dekkingsgraad eIDAS hoog voor de doelgroep "persoon die online inlogt". Niveau "substantieel" is waarschijnlijk al een te hoge drempel in het kader van inclusiviteit

**Comment by stevenvegt** [comment]
Besproken op 22 maart, als we heel letterlijk lezen, dan lijkt het alsof de beheerder van de voorziening met eIDAS hoog moet inloggen, maar we denken dat het bedoeld is voor betrokkene en behandelaar.

**Comment by stevenvegt** [comment]
Komt ter vervallen ten gunsten van #67, #68, #69
