### ISSUE TITLE
[Req 33]: We gaan door ontwikkelen op Mitz als voorziening

### ISSUE THREAD

**Issue by MLHoekstra** [minvws/generiekefuncties-toestemming#33]
# Voorstel nieuwe formaat
Als X van de voorziening wil ik dat Mitz wordt doorontwikkeld zodat ...

# Overwegingen
* Verschillende perspectieven hebben andere belangen.
* Bovenwater krijgen voor wie dit waarom belangrijk is en kijken of de requirement uiteen valt in een aantal losse requirments.

# Mogelijke invullingen?

**Zorgaanbieder**
- Wil geen desinvestering op het informeren van de patiënten over Mitz

**Betrokkene**
- Wil state of the art beveiliging
- Wil dat het blijft werken op de nieuwe telefoon

**IT leverancier**
- Wil geen desinvestering op de integratie
- Wil gebruik kunnen maken van nieuwe technologie

**Comment by VincentvandenBerg** [comment]
Dit is geen eis en waarom zou dit benoemd moeten worden?

**Comment by stevenvegt** [comment]
Dit is een kader van deze werkgroep en onderdeel van de opdracht. Kan daarom dicht.
